DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS alarm;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE alarm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enabled BOOLEAN NOT NULL,
  days VARCHAR(20) NOT NULL,
  hour INTEGER NOT NULL,
  minute INTEGER NOT NULL
);